name: Assigned issues to in progress

on:
  issues:
    types: [assigned]
  
jobs:
  assigned-to-in-progress:
    name: Move assigned to In Progress
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Testing
          column: In Progress
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}