name: Add PR to project
on:
  pull_request:
    types: [ready_for_review, opened]
jobs:
  call-workflow:
    if: ${{ github.event.pull_request.draft == 'false'}}
    uses: ./.github/workflows/get_project_data.yml
    with:
      column_name: Review
      issue_id: ${{ github.event.pull_request.node_id }}
    secrets: inherit