name: Add PR to project
on:
  issues:
    types:
      - opened
jobs:
  call-workflow:
    uses: ./.github/workflows/get_project_data.yml
    with:
      column_name: To do
      issue_id: ${{ github.event.issue.node_id }}
    secrets: inherit